name: Acquire activation file

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  unity-build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Unity
        uses: game-ci/setup-unity@v1
        with:
          unityVersion: 202x.x.x  # Replace this with the actual Unity version you are using

      - name: Build Unity Project for WebGL
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Windows
